In [1]:
import json
import pandas as pd

In [2]:
with open('data.json', 'r') as file:
    data = json.load(file)

print(data[0])

{'titulo': 'RV00465-24', 'cautelar': False, 'folio': 'https://portal-pautas.ine.mx/pautas5/materiales/MP4/HD/RV00465-24.mp4', 'ruta': True, 'es_publico': True, 'archivoTraduccion': 'Sin archivo', 'directorio': 'tv/PAN', 'partido': 'PAN', 'nombre': 'CAM FED SEN LLEGO LA HORA DEL CAMBIO V2', 'transcripcion': ' Hoy tienes la oportunidad única de cambiar todo lo que está mal en el gobierno federal. Queremos un México para todos. Los programas de adultos mayores que iniciaron en el gobierno panista de Fox ahora los llamaremos 60 y más y el Seguro Popular te lo regresaremos. Con Xochitl y una nueva mayoría en el Congreso se acabarán los abrazos a los criminales. Tú y nuestras familias merecen vivir en paz. Vota por las senadoras y los senadores de Acción Nacional. Por un México sin miedo llegó la hora del cambio. Vota PAN.'}


In [3]:
keys = data[0].keys()
if all(element.keys() == keys for element in data):
    # Crea un DataFrame
    df = pd.DataFrame(data)
    print(df)
else:
    print("No todos los elementos tienen las mismas llaves.")

          titulo  cautelar                                              folio   
0     RV00465-24     False  https://portal-pautas.ine.mx/pautas5/materiale...  \
1     RV00466-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
2     RV00467-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
3     RV00468-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
4     RV00470-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
...          ...       ...                                                ...   
1022  RA01907-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
1023  RA01962-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
1024  RA00316-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
1025  RA00739-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
1026  RA00164-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   

      ruta  es_publico arch

In [4]:
df.head()

titulo  cautelar                                              folio   
0  RV00465-24     False  https://portal-pautas.ine.mx/pautas5/materiale...  \
1  RV00466-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
2  RV00467-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
3  RV00468-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   
4  RV00470-24     False  https://portal-pautas.ine.mx/pautas5/materiale...   

   ruta  es_publico archivoTraduccion directorio partido   
0  True        True       Sin archivo     tv/PAN     PAN  \
1  True        True       Sin archivo     tv/PAN     PAN   
2  True        True       Sin archivo     tv/PAN     PAN   
3  True        True       Sin archivo     tv/PAN     PAN   
4  True        True       Sin archivo     tv/PAN     PAN   

                                     nombre   
0   CAM FED SEN LLEGO LA HORA DEL CAMBIO V2  \
1   CAM FED SEN LLEGO LA HORA DE AVANZAR V1   
2  CAM FED SEN QRO AVANZAR AGUSTIN DORANTES   
3     CAM FED SEN MICH CAMBIO BETO LUCATERO   
4      CAM FED SEN SIN CAMBIO EDUARDO ORTIZ   

                                       transcripcion  
0   Hoy tienes la oportunidad única de cambiar to...  
1   Hoy tienes la oportunidad única de cambiar to...  
2   Ya basta de vivir con miedo. Con una nueva ma...  
3   Ya basta de vivir con miedo. Con una nueva ma...  
4   Ya basta de vivir con miedo. Con una nueva ma...

In [ ]:
# import os
# import pandas as pd
# import re

# # Path to the folder containing the Excel files
# folder_path = 'Transmisiones'

# # Function to extract period from a given string
# def extract_period(period_str):
#     match = re.search(r'(\d{2}/\d{2}/\d{4}) al (\d{2}/\d{2}/\d{4})', period_str)
#     if match:
#         start_date = match.group(1).replace('/', '_')
#         end_date = match.group(2).replace('/', '_')
#         return start_date, end_date
#     return None, None

# # List to keep track of newly created files
# new_files = []

# # Loop through all the files in the folder
# for file_name in os.listdir(folder_path):
#     if file_name.endswith('.xlsx'):
#         file_path = os.path.join(folder_path, file_name)
        
#         # Load the Excel file
#         xls = pd.ExcelFile(file_path)
        
#         # Process the "Excedentes" sheet
#         if 'Excedentes' in xls.sheet_names:
#             df_excedentes = pd.read_excel(xls, 'Excedentes')
#             period_str = df_excedentes.iloc[5, 0]  # A7 is the 7th row (index 6)
#             start_date, end_date = extract_period(period_str)
#             if start_date and end_date:
#                 new_file_name = f'Excedentes_{start_date}_{end_date}.xlsx'
#                 new_file_path = os.path.join(folder_path, new_file_name)
#                 df_excedentes.to_excel(new_file_path, index=False)
#                 new_files.append(new_file_name)
        
#         # Process the "Requerimientos por excedentes" sheet
#         if 'Requerimientos por excedentes' in xls.sheet_names:
#             df_requerimientos = pd.read_excel(xls, 'Requerimientos por excedentes')
#             period_str = df_requerimientos.iloc[7, 0]  # A9 is the 9th row (index 8)
#             start_date, end_date = extract_period(period_str)
#             if start_date and end_date:
#                 new_file_name = f'Requerimientos_{start_date}_{end_date}.xlsx'
#                 new_file_path = os.path.join(folder_path, new_file_name)
#                 df_requerimientos.to_excel(new_file_path, index=False)
#                 new_files.append(new_file_name)


Aquí

In [7]:
import os
import pandas as pd

# Path to the folder containing the Excel files
folder_path = 'Transmisiones'

# Function to delete the first N rows of an Excel file
def delete_first_n_rows(file_path, n):
    df = pd.read_excel(file_path, header=None)  # Read without header
    df = df.iloc[n:]  # Drop the first n rows
    df.columns = df.iloc[0]  # Set the first row as header
    df = df[1:]  # Drop the header row
    df.to_excel(file_path, index=False)

# Loop through all the files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.xlsx'):
        file_path = os.path.join(folder_path, file_name)
        
        if file_name.startswith('Requerimientos_'):
            delete_first_n_rows(file_path, 11)
        
        elif file_name.startswith('Excedentes_'):
            delete_first_n_rows(file_path, 8)



In [3]:
import os
import pandas as pd

# Path to the folder containing the Excel files
folder_path = 'Transmisiones'

# Function to convert an Excel file to CSV
def convert_to_csv(file_path, csv_path):
    df = pd.read_excel(file_path)  # Read the Excel file
    df.to_csv(csv_path, index=False)  # Convert to CSV

# Loop through all the files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.xlsx'):
        file_path = os.path.join(folder_path, file_name)
        
        # Define the path for the CSV file
        csv_file_name = file_name.replace('.xlsx', '.csv')
        csv_path = os.path.join(folder_path, csv_file_name)
        
        # Convert the Excel file to CSV
        convert_to_csv(file_path, csv_path)

print("Conversion completed.")


Conversion completed.


In [15]:
import os
import pandas as pd

# Path to the folder containing the Excel files
folder_path = 'Transmisiones'

# Lists to store DataFrames
excedentes_list = []
requerimientos_list = []

# Loop through all the files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.xlsx'):
        file_path = os.path.join(folder_path, file_name)
        
        if file_name.startswith('Excedentes_'):
            df = pd.read_excel(file_path)
            excedentes_list.append(df)
        
        elif file_name.startswith('Requerimientos_'):
            df = pd.read_excel(file_path)
            requerimientos_list.append(df)

# Concatenate and sort DataFrames in each list
if excedentes_list:
    excedentes_combined = pd.concat(excedentes_list, ignore_index=True)
    excedentes_combined['FECHA TRANSMISIÓN'] = pd.to_datetime(excedentes_combined['FECHA TRANSMISIÓN'], format='%d/%m/%Y')
    excedentes_combined['HORA TRANSMISIÓN'] = pd.to_datetime(excedentes_combined['HORA TRANSMISIÓN'], format='%H:%M:%S').dt.time
    excedentes_combined = excedentes_combined.sort_values(by=['FECHA TRANSMISIÓN', 'HORA TRANSMISIÓN'])
    excedentes_combined.to_csv(os.path.join(folder_path, 'Excedentes_combined.csv'), index=False)

if requerimientos_list:
    requerimientos_combined = pd.concat(requerimientos_list, ignore_index=True)
    requerimientos_combined['Fecha de transmisión del material'] = pd.to_datetime(requerimientos_combined['Fecha de transmisión del material'], dayfirst=True)
    requerimientos_combined = requerimientos_combined.sort_values(by=['Fecha de transmisión del material', 'Hora transmisión'])
    requerimientos_combined.to_csv(os.path.join(folder_path, 'Requerimientos_combined.csv'), index=False)

print('Archivos combinados creados exitosamente en formato CSV, ordenados por fecha y hora.')


Archivos combinados creados exitosamente en formato CSV, ordenados por fecha y hora.


In [16]:
import os
import pandas as pd

# Path to the folder containing the combined CSV files
folder_path = 'Transmisiones'

# Function to count the number of rows in a CSV file
def count_rows(file_path):
    df = pd.read_csv(file_path)
    return len(df)

# Function to count duplicate rows in a DataFrame
def count_duplicates(df):
    return df.duplicated().sum()

# Function to read a CSV file into a DataFrame
def read_csv_file(file_path):
    return pd.read_csv(file_path)

# Function to count duplicates based on specific columns between two DataFrames
def count_cross_duplicates(df1, df2, df1_columns, df2_columns):
    df1_subset = df1[df1_columns].copy()
    df2_subset = df2[df2_columns].copy()

    # Ensure the columns are of the same type (string)
    for col in df1_columns:
        df1_subset[col] = df1_subset[col].astype(str)
    for col in df2_columns:
        df2_subset[col] = df2_subset[col].astype(str)

    merged_df = pd.merge(df1_subset, df2_subset, left_on=df1_columns, right_on=df2_columns)
    return len(merged_df)

# File names of the combined CSV files
excedentes_combined_file = 'Excedentes_combined.csv'
requerimientos_combined_file = 'Requerimientos_combined.csv'

# Full paths to the combined CSV files
excedentes_combined_path = os.path.join(folder_path, excedentes_combined_file)
requerimientos_combined_path = os.path.join(folder_path, requerimientos_combined_file)

# Check if the combined files exist and count the rows
if os.path.exists(excedentes_combined_path):
    excedentes_row_count = count_rows(excedentes_combined_path)
    print(f'El archivo {excedentes_combined_file} tiene {excedentes_row_count} renglones.')

if os.path.exists(requerimientos_combined_path):
    requerimientos_row_count = count_rows(requerimientos_combined_path)
    print(f'El archivo {requerimientos_combined_file} tiene {requerimientos_row_count} renglones.')

# Read the files and count duplicates within each file
if os.path.exists(excedentes_combined_path):
    df_excedentes = read_csv_file(excedentes_combined_path)
    excedentes_duplicates = count_duplicates(df_excedentes)
    print(f'El archivo {excedentes_combined_file} tiene {excedentes_duplicates} registros repetidos dentro del archivo.')

if os.path.exists(requerimientos_combined_path):
    df_requerimientos = read_csv_file(requerimientos_combined_path)
    requerimientos_duplicates = count_duplicates(df_requerimientos)
    print(f'El archivo {requerimientos_combined_file} tiene {requerimientos_duplicates} registros repetidos dentro del archivo.')

# Check for duplicates between the two files based on specific columns
if os.path.exists(excedentes_combined_path) and os.path.exists(requerimientos_combined_path):
    cross_duplicates = count_cross_duplicates(
        df_excedentes,
        df_requerimientos,
        df1_columns=['ESTADO', 'FECHA TRANSMISIÓN', 'HORA TRANSMISIÓN'],
        df2_columns=['Entidad', 'Fecha de transmisión del material', 'Hora transmisión']
    )
    print(f'Entre los archivos {excedentes_combined_file} y {requerimientos_combined_file} hay {cross_duplicates} registros repetidos basados en las columnas especificadas.')


El archivo Excedentes_combined.csv tiene 78842 renglones.
El archivo Requerimientos_combined.csv tiene 45569 renglones.
El archivo Excedentes_combined.csv tiene 0 registros repetidos dentro del archivo.
El archivo Requerimientos_combined.csv tiene 0 registros repetidos dentro del archivo.
Entre los archivos Excedentes_combined.csv y Requerimientos_combined.csv hay 38452 registros repetidos basados en las columnas especificadas.


El archivo Excedentes_combined.csv tiene 78842 renglones.
El archivo Requerimientos_combined.csv tiene 45569 renglones.
El archivo Excedentes_combined.csv tiene 0 registros repetidos dentro del archivo.
El archivo Requerimientos_combined.csv tiene 0 registros repetidos dentro del archivo.
Entre los archivos Excedentes_combined.csv y Requerimientos_combined.csv hay 38452 registros repetidos basados en las columnas especificadas.

In [17]:
import os
import pandas as pd

# Path to the folder containing the combined CSV files
folder_path = 'Transmisiones'

# Function to read a CSV file into a DataFrame
def read_csv_file(file_path):
    return pd.read_csv(file_path)

# Function to find and remove cross-duplicates from df2 based on df1
def remove_cross_duplicates(df1, df2, df1_columns, df2_columns):
    df1_subset = df1[df1_columns].copy()
    df2_subset = df2[df2_columns].copy()

    # Ensure the columns are of the same type (string)
    for col in df1_columns:
        df1_subset[col] = df1_subset[col].astype(str)
    for col in df2_columns:
        df2_subset[col] = df2_subset[col].astype(str)

    merged_df = pd.merge(df2, df1_subset, how='left', left_on=df2_columns, right_on=df1_columns, indicator=True)
    df2_cleaned = merged_df[merged_df['_merge'] == 'left_only'].drop(columns=['_merge'])

    return df2_cleaned

# File names of the combined CSV files
excedentes_combined_file = 'Excedentes_combined.csv'
requerimientos_combined_file = 'Requerimientos_combined.csv'

# Full paths to the combined CSV files
excedentes_combined_path = os.path.join(folder_path, excedentes_combined_file)
requerimientos_combined_path = os.path.join(folder_path, requerimientos_combined_file)

# Check if the combined files exist and read them
if os.path.exists(excedentes_combined_path) and os.path.exists(requerimientos_combined_path):
    df_excedentes = read_csv_file(excedentes_combined_path)
    df_requerimientos = read_csv_file(requerimientos_combined_path)

    # Remove duplicates from requerimientos based on excedentes
    df_requerimientos_cleaned = remove_cross_duplicates(
        df_excedentes,
        df_requerimientos,
        df1_columns=['ESTADO', 'FECHA TRANSMISIÓN', 'HORA TRANSMISIÓN'],
        df2_columns=['Entidad', 'Fecha de transmisión del material', 'Hora transmisión']
    )

    # Save the cleaned DataFrame to a new CSV file or overwrite the existing one
    df_requerimientos_cleaned.to_csv(requerimientos_combined_path, index=False)
    print(f'Se han eliminado los registros duplicados del archivo {requerimientos_combined_file}.')
else:
    print(f'No se encontraron uno o ambos archivos: {excedentes_combined_file}, {requerimientos_combined_file}.')


Se han eliminado los registros duplicados del archivo Requerimientos_combined.csv.


In [24]:
import os
import pandas as pd

# Path to the folder containing the combined CSV files
folder_path = 'Transmisiones'

# Function to read a CSV file into a DataFrame
def read_csv_file(file_path):
    return pd.read_csv(file_path)

# Function to rename columns in a DataFrame
def rename_columns(df, columns_mapping):
    return df.rename(columns=columns_mapping)

# Function to standardize date and time formats
def standardize_datetime(df, date_col, time_col):
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce').dt.strftime('%Y-%m-%d')
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce').dt.strftime('%H:%M:%S')
    return df

# File names of the combined CSV files
excedentes_combined_file = 'Excedentes_combined.csv'
requerimientos_combined_file = 'Requerimientos_combined.csv'

# Full paths to the combined CSV files
excedentes_combined_path = os.path.join(folder_path, excedentes_combined_file)
requerimientos_combined_path = os.path.join(folder_path, requerimientos_combined_file)

# Column mapping for renaming
columns_mapping = {
    'Entidad': 'ESTADO',
    'Emisora': 'EMISORA',
    'Versión': 'VERSIÓN',
    'Folio': 'MATERIAL',
    'Actor': 'ACTOR',
    'Fecha de transmisión del material': 'FECHA TRANSMISIÓN',
    'Hora transmisión': 'HORA TRANSMISIÓN'
}

# Check if the combined files exist and read them
if os.path.exists(excedentes_combined_path) and os.path.exists(requerimientos_combined_path):
    df_excedentes = read_csv_file(excedentes_combined_path)
    df_requerimientos = read_csv_file(requerimientos_combined_path)

    # Rename columns in df_requerimientos
    df_requerimientos_renamed = rename_columns(df_requerimientos, columns_mapping)

    # Remove duplicate columns before any further processing
    df_excedentes = df_excedentes.loc[:, ~df_excedentes.columns.duplicated()]
    df_requerimientos_renamed = df_requerimientos_renamed.loc[:, ~df_requerimientos_renamed.columns.duplicated()]

    # Standardize date and time formats
    df_excedentes = standardize_datetime(df_excedentes, 'FECHA TRANSMISIÓN', 'HORA TRANSMISIÓN')
    df_requerimientos_renamed = standardize_datetime(df_requerimientos_renamed, 'FECHA TRANSMISIÓN', 'HORA TRANSMISIÓN')

    # Reset index for both DataFrames to avoid InvalidIndexError
    df_excedentes.reset_index(drop=True, inplace=True)
    df_requerimientos_renamed.reset_index(drop=True, inplace=True)

    # Combine the DataFrames with outer join to include all columns
    combined_df = pd.concat([df_excedentes, df_requerimientos_renamed], ignore_index=True, sort=False, join='outer')

    # Save the combined DataFrame to a new CSV file
    combined_file_path = os.path.join(folder_path, 'Transmisiones.csv')
    combined_df.to_csv(combined_file_path, index=False)
    print(f'Se han combinado y guardado los archivos en {combined_file_path}.')
else:
    print(f'No se encontraron uno o ambos archivos: {excedentes_combined_file}, {requerimientos_combined_file}.')


C:\Users\52552\AppData\Local\Temp\ipykernel_11896\4079119933.py:18: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[time_col] = pd.to_datetime(df[time_col], errors='coerce').dt.strftime('%H:%M:%S')
C:\Users\52552\AppData\Local\Temp\ipykernel_11896\4079119933.py:18: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[time_col] = pd.to_datetime(df[time_col], errors='coerce').dt.strftime('%H:%M:%S')


Se han combinado y guardado los archivos en Transmisiones\Combined_Spots.csv.
